services:
  backend:
    build:
      context: ./vuelosBackend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: development
      IA_API_BASE_URL: http://ia-api:3020/api
    depends_on:
      - ia-api
    networks:
      - melincue-network

  frontend:
    build:
      context: ./vuelosFrontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_IA_API_URL: http://ia-api:3020
      NEXT_PUBLIC_BACKEND_API_URL: http://backend:3030
    depends_on:
      - backend
      - ia-api
    networks:
      - melincue-network

  ia-api:
    build:
      context: ./vuelosIA/api-js
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    environment:
      NODE_ENV: development
      BACKEND_API_URL: http://backend:3030
      OPENAI_API_KEY: ${OPENAI_API_KEY}    # <--- Acá la variable
    volumes:
      - ./vuelosIA/api-js/data:/app/data
    networks:
      - melincue-network

networks:
  melincue-network:
    driver: bridge
